FROM python:3.11-slim

WORKDIR /app

COPY streamlit_app.py .

RUN pip install streamlit requests

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]